/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.60
 * Generated at: 2021-02-27 13:01:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import g.g.d.com.mem.common.TempPassword;

public final class registerForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("g.g.d.com.mem.common.TempPassword");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<!-- 디바이스에 최적화된 크기로 출력됨 -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\r\n");
      out.write("      maximum-scale=1.0, minimum-scale=1.0, user-scalable=no\">\r\n");
      out.write("<!-- 추가 -->\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("<script src=\"//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!------ Include the above in your HEAD tag ---------->\r\n");
      out.write("\r\n");
      out.write("<title>GOGODA 회원 가입</title>\r\n");
      out.write("\r\n");
      out.write("<!-- daum 도로명주소 찾기 api -->\r\n");
      out.write("<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("//모든 공백 체크 정규식 \r\n");
      out.write("var empJ = /\\s/g; \r\n");
      out.write("//아이디 정규식 \r\n");
      out.write("var idJ = /^[a-z0-9][a-z0-9_\\-]{4,19}$/; \r\n");
      out.write("//비밀번호 정규식 \r\n");
      out.write("var pwJ = /^[A-Za-z0-9]{4,12}$/;\r\n");
      out.write("//이름 정규식 \r\n");
      out.write("var nameJ = /^[가-힣]{2,4}|[a-zA-Z]{2,10}\\s[a-zA-Z]{2,10}$/; \r\n");
      out.write("//이메일 검사 정규식 \r\n");
      out.write("var emailJ = /^[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*.[a-zA-Z]{2,3}$/i; \r\n");
      out.write("//휴대폰 번호 정규식 \r\n");
      out.write("var phoneJ = /^01([0|1|6|7|8|9]?)?([0-9]{3,4})?([0-9]{4})$/; \r\n");
      out.write("/^[가-힣]{2,4}|[a-zA-Z]{2,10}\\s[a-zA-Z]{2,10}$/ \r\n");
      out.write("\r\n");
      out.write("var birthJ = false; \r\n");
      out.write("\r\n");
      out.write("var address = $('#maddrdetail'); \r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\r\n");
      out.write("\t//*****************************************************\r\n");
      out.write("\tvar oldmid='';\r\n");
      out.write("\tvar key='';\r\n");
      out.write("\tvar mnum='';\r\n");
      out.write("\tvar oldmemail='';\r\n");
      out.write("\t// mnum hidden\r\n");
      out.write("\t$('#mnum').hide();\r\n");
      out.write("\t\r\n");
      out.write("\tvar address = $('#maddrdetail'); \r\n");
      out.write("\t\r\n");
      out.write("\t//아이디 중복확인 \r\n");
      out.write("\t$(\"#mid\").blur(function() { \r\n");
      out.write("\t\tif(oldmid!=''){\r\n");
      out.write("\t\t\tif(oldmid!=$('#mid').val()){\r\n");
      out.write("\t\t\t\t$('#id_check').text('다시 중복 확인을 해주십시오'); \r\n");
      out.write("\t            $('#id_check').css('color', 'red'); \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(oldmid==$('#mid').val()){\r\n");
      out.write("\t\t\t\t$('#id_check').text('확인 완료'); \r\n");
      out.write("\t            $('#id_check').css('color', 'green'); \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("    });\r\n");
      out.write("\t$(\"#memail\").blur(function(){\r\n");
      out.write("\t\tif(oldmemail!=''){\r\n");
      out.write("\t\t\tif(oldmemail!=$('#memail').val()){\r\n");
      out.write("\t\t\t\t$('#code_check').text('이메일 내용이 변동되었습니다. 다시 체크해주세요'); \r\n");
      out.write("\t            $('#code_check').css('color', 'red'); \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(oldmemail==$('#memail').val()){\r\n");
      out.write("\t\t\t\t$('#code_check').text('인증 완료!'); \r\n");
      out.write("\t            $('#code_check').css('color', 'green'); \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t//*****************************************************\r\n");
      out.write("\t\r\n");
      out.write("\t//*****************************************************\r\n");
      out.write("\t// id 중복확인  \t\r\n");
      out.write("    $(document).on(\"click\", \"#midbtn\", function(){\r\n");
      out.write("    \tconsole.log(\"midbtn >>> : \");\r\n");
      out.write("    \talert(\"midbtn >>> : \"+$('#mid').val().length);\r\n");
      out.write("        if($('#mid').val().length>=5){ \r\n");
      out.write("\t    \tlet idcheckURL = \"idCheck.ggd\";\r\n");
      out.write("\t    \tlet method = \"POST\";\r\n");
      out.write("\t    \tlet midVal = $('#mid').val();\r\n");
      out.write("\t         \r\n");
      out.write("\t    \tlet dataParam = {\"mid\": midVal};\r\n");
      out.write("\t         \r\n");
      out.write("\t    \t$.ajax({\r\n");
      out.write("\t        \turl: idcheckURL,\r\n");
      out.write("\t            type: method, \r\n");
      out.write("\t            data: dataParam,\r\n");
      out.write("\t            success: whenSuccess,\r\n");
      out.write("\t            error: whenError\r\n");
      out.write("\t        });\r\n");
      out.write("\t         \r\n");
      out.write("\t        function whenSuccess(resData){\r\n");
      out.write("\t        \talert(resData);\r\n");
      out.write("\t            var sVal = resData;   \r\n");
      out.write("\t            if ('ID_GOOD' == sVal){\r\n");
      out.write("\t               alert(\"사용할 수 있는 아이디 입니다.\");\r\n");
      out.write("\t               $('#id_check').text('확인 완료'); \r\n");
      out.write("\t               $('#id_check').css('color', 'green'); \r\n");
      out.write("\t               oldmid=$('#mid').val()\r\n");
      out.write("\t            }else{\r\n");
      out.write("\t               alert(\"이미 사용 중인 아이디입니다.\");\r\n");
      out.write("\t               $('#id_check').text(''); \r\n");
      out.write("\t               $('#id_check').css('color', 'red'); \r\n");
      out.write("\t               $(\"#mid\").val('');\r\n");
      out.write("\t               $(\"#mid\").focus();\r\n");
      out.write("\t            }\r\n");
      out.write("\t         }\r\n");
      out.write("\t\t\tfunction whenError(){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t        }\r\n");
      out.write("        }else{\r\n");
      out.write("        \talert(\"아이디를 제대로 입력해주십시오.\");\r\n");
      out.write("            $('#id_check').text('5~20자의 영문 소문자, 숫자와 특수기호(_),(-)만 사용 가능합니다.'); \r\n");
      out.write("            $('#id_check').css('color', 'red'); \r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("  //*****************************************************\r\n");
      out.write("\r\n");
      out.write("/////////////////////////////////////////////////////////////////////////////////////\r\n");
      out.write("//$(function() {\r\n");
      out.write("\tvar isCertification = false;\r\n");
      out.write("\r\n");
      out.write("\t$(\"#memailbtn\").click(function() {// 메일 입력 유효성 검사\r\n");
      out.write("\t\tvar mail = $(\"#memail\").val(); // 사용자의 이메일 입력값.\r\n");
      out.write("\t\tif (mail == \"\") {\r\n");
      out.write("\t\t\talert(\"메일 주소가 입력되지 않았습니다.\");\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\talert(\"인증코드를 발송하였습니다.\\n이메일을 확인하시기 바랍니다.\");\r\n");
      out.write("\t\t\t//returnGetData(meail);\r\n");
      out.write("\t\t\t//mail = mail + \"@\" + $(\".domain\").val(); // 셀렉트 박스에 @뒤 값들을 더함.\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\turl : 'mailCheck.ggd',\r\n");
      out.write("\t\t\t\tdataType : 'text',\r\n");
      out.write("\t\t\t\tasync : false,\r\n");
      out.write("\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\"mail\" : mail\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess : whenSuccess,\r\n");
      out.write("\t\t\t\terror: whenError\r\n");
      out.write("\t\t\t});\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#emcode\").css(\"display\", \"block\");\r\n");
      out.write("\t\t\t$(\"#code_check\").css(\"display\", \"block\");\r\n");
      out.write("\t\t\tfunction whenSuccess(keyData) {\r\n");
      out.write("\t\t\t\tkey=keyData;\r\n");
      out.write("\t\t\t\tconsole.log(keyData);\t\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfunction whenError(){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write(" //});   \r\n");
      out.write("      // 인증 키 일치여부 확인 \r\n");
      out.write("      $(\"#emcode\").on(\"propertychange change keyup paste input\", function() {\r\n");
      out.write("    \t//alert(\"key>>>\"+key);\r\n");
      out.write("  \t\tif ($(\"#emcode\").val() == key) {\r\n");
      out.write("  \t\t\t$(\"#code_check\").text(\"인증 완료!\").css(\"color\", \"green\");\r\n");
      out.write("  \t\t\toldmemail=$(\"#memail\").val();\r\n");
      out.write("  \t\t\tisCertification = true;\r\n");
      out.write("  \t\t} else {\r\n");
      out.write("  \t\t\t$(\"#code_check\").text(\"다시 확인하여 주시기 바랍니다.\").css(\"color\", \"red\");\r\n");
      out.write("  \t\t\tisCertification = false;\r\n");
      out.write("  \t\t}\r\n");
      out.write("  \t});\r\n");
      out.write("      \r\n");
      out.write("      // 회원 가입 전 메일 인증 여부 확인\r\n");
      out.write("      // 메일 인증이 되었다면 submit버튼을 클릭하면 서버측으로 사용자의 입력값이 전송됩니다.\r\n");
      out.write("      \r\n");
      out.write("  /////////////////////////////////////////////////////////////////////////////////////\t\r\n");
      out.write("//*****************************************************\r\n");
      out.write("    $(document).on(\"click\",\"#submitBtn\",function(){ \r\n");
      out.write("    \tvar checkMember=0;\r\n");
      out.write("    \tif($('#id_check').text()!='확인 완료'){\r\n");
      out.write("    \t\talert('아이디를 확인하세요.');\r\n");
      out.write("    \t\treturn false;\r\n");
      out.write("    \t}else{checkMember=checkMember+1;}//1\r\n");
      out.write("    \t\r\n");
      out.write("    \tif($('#zipcode').val()==''){\r\n");
      out.write("            alert('우편번호를 확인하세요.'); \r\n");
      out.write("            return false; \r\n");
      out.write("    \t}else{checkMember=checkMember+1;}//2\r\n");
      out.write("    \tif($('#maddrdetail').val()==''){\r\n");
      out.write("    \t\talert('상세 주소를 확인해주세요.');\r\n");
      out.write("    \t\treturn false;\r\n");
      out.write("    \t}else{checkMember=checkMember+1;}//3\r\n");
      out.write("    \tif($('#code_check').text()!='인증 완료!'){\r\n");
      out.write("    \t\talert('인증코드를 확인해주세요.');\r\n");
      out.write("    \t\treturn false;\r\n");
      out.write("    \t}else{checkMember=checkMember+1;}//4\r\n");
      out.write("    \t\r\n");
      out.write("    \t// 아이디 정규식\r\n");
      out.write("\t\tvar inval_Arr = new Array(8).fill(false); \r\n");
      out.write("        if (idJ.test($('#mid').val())) { \r\n");
      out.write("        \tinval_Arr[0] = true; \r\n");
      out.write("        \tcheckMember=checkMember+1;//5\r\n");
      out.write("        } else { \r\n");
      out.write("           inval_Arr[0] = false; \r\n");
      out.write("           alert('아이디를 확인하세요.'); \r\n");
      out.write("           return false; \r\n");
      out.write("        } \r\n");
      out.write("        \r\n");
      out.write("        // 비밀번호가 같은 경우 && 비밀번호 정규식 \r\n");
      out.write("        if (($('#mpw').val() == ($('#mpw2').val())) && pwJ.test($('#mpw').val())) { \r\n");
      out.write("           inval_Arr[1] = true;\r\n");
      out.write("           checkMember=checkMember+1;//6\r\n");
      out.write("        } else { \r\n");
      out.write("           inval_Arr[1] = false; \r\n");
      out.write("           alert('비밀번호를 확인하세요.'); \r\n");
      out.write("           return false; \r\n");
      out.write("        } \r\n");
      out.write("        \r\n");
      out.write("        // 이름 정규식 \r\n");
      out.write("        if (nameJ.test($('#mname').val())) { \r\n");
      out.write("           inval_Arr[2] = true; \r\n");
      out.write("           checkMember=checkMember+1;//7\r\n");
      out.write("        } else { inval_Arr[2] = false; \r\n");
      out.write("           alert('이름을 확인하세요.'); \r\n");
      out.write("           return false; \r\n");
      out.write("        } \r\n");
      out.write("        \r\n");
      out.write("        // 생년월일 정규식 \r\n");
      out.write("        if (birthJ) { \r\n");
      out.write("           console.log(birthJ); \r\n");
      out.write("           inval_Arr[3] = true; \r\n");
      out.write("           checkMember=checkMember+1;//8\r\n");
      out.write("        } else { \r\n");
      out.write("           inval_Arr[3] = false; \r\n");
      out.write("           alert('생년월일을 확인하세요.'); \r\n");
      out.write("           return false; \r\n");
      out.write("        } \r\n");
      out.write("        \r\n");
      out.write("        // 이메일 정규식 \r\n");
      out.write("        if (emailJ.test($('#memail').val())){ \r\n");
      out.write("           console.log(phoneJ.test($('#memail').val())); \r\n");
      out.write("           inval_Arr[4] = true;\r\n");
      out.write("           checkMember=checkMember+1;//9\r\n");
      out.write("        } else { \r\n");
      out.write("           inval_Arr[4] = false; \r\n");
      out.write("           alert('이메일을 확인하세요.'); \r\n");
      out.write("           return false; \r\n");
      out.write("        } \r\n");
      out.write("        \r\n");
      out.write("        // 휴대폰번호 정규식\r\n");
      out.write("        if (phoneJ.test($('#mhp').val())) { \r\n");
      out.write("           console.log(phoneJ.test($('#mhp').val())); \r\n");
      out.write("           inval_Arr[5] = true;\r\n");
      out.write("           checkMember=checkMember+1;//10\r\n");
      out.write("        } else { \r\n");
      out.write("           inval_Arr[5] = false; \r\n");
      out.write("           alert('휴대폰 번호를 확인하세요.'); \r\n");
      out.write("           return false; \r\n");
      out.write("        } \r\n");
      out.write("        \r\n");
      out.write("        //주소확인\r\n");
      out.write("        if(address.val() == ''){ \r\n");
      out.write("           inval_Arr[7] = false; \r\n");
      out.write("           alert('주소를 확인하세요.'); \r\n");
      out.write("           return false; \r\n");
      out.write("        }else {\r\n");
      out.write("           inval_Arr[7] = true;\r\n");
      out.write("           checkMember=checkMember+1;//11\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\t\tif(checkMember<=11){ // 유효성 모두 통과 \r\n");
      out.write("           \talert('고고다의 회원이 되어주셔서 감사합니다.'); \r\n");
      out.write("           \tlet idcheckURL = \"memberInsert.ggd\";\r\n");
      out.write("\t    \tlet method = \"POST\";\r\n");
      out.write("\t    \tlet mname=$('#mname').val();\r\n");
      out.write("\t    \tlet mid=$('#mid').val();\r\n");
      out.write("\t    \tlet mpw=$('#mpw').val();\r\n");
      out.write("\t    \tlet mbirth=$('#mbirth').val();\r\n");
      out.write("\t    \tlet mgender=$('#mgender').val();\r\n");
      out.write("\t    \tlet mhp=$('#mhp').val();\r\n");
      out.write("\t    \tlet memail=$('#memail').val();\r\n");
      out.write("\t    \tlet mzipcode=$('#mzipcode').val();\r\n");
      out.write("\t    \tlet maddr=$('#maddr').val();\r\n");
      out.write("\t    \tlet maddrdetail=$('#maddrdetail').val();\r\n");
      out.write("\t    \t$.ajax({\r\n");
      out.write("\t\t\t\ttype : 'POST',\r\n");
      out.write("\t\t\t\turl : 'memberInsert.ggd',\r\n");
      out.write("\t\t\t\tdataType : 'text',\r\n");
      out.write("\t\t\t\tasync : false,\r\n");
      out.write("\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\"mname\":mname,\r\n");
      out.write("\t    \t\t\t\"mid\":mid,\r\n");
      out.write("\t    \t\t\t\"mpw\":mpw,\r\n");
      out.write("\t    \t\t\t\"mbirth\":mbirth,\r\n");
      out.write("\t    \t\t\t\"mgender\":mgender,\r\n");
      out.write("\t    \t\t\t\"mhp\":mhp,\r\n");
      out.write("\t    \t\t\t\"memail\":memail,\r\n");
      out.write("\t    \t\t\t\"mzipcode\":mzipcode,\r\n");
      out.write("\t    \t\t\t\"maddr\":maddr,\r\n");
      out.write("\t    \t\t\t\"maddrdetail\":maddrdetail\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess : whenSuccess,\r\n");
      out.write("\t\t\t\terror : whenError});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t    \t\tfunction whenSuccess(data) {\r\n");
      out.write("\t    \t\t\tconsole.log(data);\r\n");
      out.write("\t    \t\t\tmnum=data;\r\n");
      out.write("\t    \t\t\talert(mnum);\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\ttype : 'POST',\r\n");
      out.write("\t\t\t\t\t\turl : 'moveSurvey.ggd',\r\n");
      out.write("\t\t\t\t\t\tdataType : \"html\",\r\n");
      out.write("\t\t\t\t\t\tdata:mnum,\r\n");
      out.write("\t\t\t\t\t\tcache : false\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t.done(function(dataHtml){\r\n");
      out.write("\t\t\t\t\t\talert(dataHtml);\r\n");
      out.write("\t\t\t\t\t\tdataHtml=dataHtml+\"\\n<input type='hidden' id='mnum' name='mnum' value='\"+mnum+\"'>\";\r\n");
      out.write("\t\t\t\t\t\t$('#memForm').children().remove();\r\n");
      out.write("\t\t\t\t\t\t$('#memForm').html(dataHtml);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t    \t\tfunction whenError(){\r\n");
      out.write("\t    \t\t\t\r\n");
      out.write("\t    \t\t}\r\n");
      out.write("        } else{ \r\n");
      out.write("           \talert('정보를 다시 확인하세요.') \r\n");
      out.write("        }\r\n");
      out.write("     });\r\n");
      out.write("  //*****************************************************\r\n");
      out.write("     $('#mid').blur(function() { \r\n");
      out.write("        if (idJ.test($('#mid').val())) { \r\n");
      out.write("           console.log('true'); \r\n");
      out.write("        } else { \r\n");
      out.write("           console.log('false'); \r\n");
      out.write("           $('#id_check').text('5~20자의 영문 소문자, 숫자와 특수기호(_),(-)만 사용 가능합니다.'); \r\n");
      out.write("           $('#id_check').css('color', 'red'); \r\n");
      out.write("        } \r\n");
      out.write("     }); \r\n");
      out.write("   //*****************************************************\r\n");
      out.write("     \r\n");
      out.write("     $('#mpw').blur(function() { \r\n");
      out.write("        if (pwJ.test($('#mpw').val())) { \r\n");
      out.write("           console.log('true'); \r\n");
      out.write("           $('#pw_check').text(''); \r\n");
      out.write("        } else { \r\n");
      out.write("           console.log('false'); \r\n");
      out.write("           $('#pw_check').text('4~12자의 숫자 , 문자로만 사용 가능합니다.'); \r\n");
      out.write("           $('#pw_check').css('color', 'red');\r\n");
      out.write("        } \r\n");
      out.write("     }); \r\n");
      out.write("     \r\n");
      out.write("     //1~2 패스워드 일치 확인 \r\n");
      out.write("     $('#mpw2').blur(function() { \r\n");
      out.write("        if ($('#mpw').val() != $(this).val()) { \r\n");
      out.write("           $('#pw2_check').text('비밀번호가 일치하지 않습니다.'); \r\n");
      out.write("           $('#pw2_check').css('color', 'red'); \r\n");
      out.write("        } else { $('#pw2_check').text(''); \r\n");
      out.write("       \t} \r\n");
      out.write("     }); \r\n");
      out.write("     \r\n");
      out.write("     //이름에 특수문자 들어가지 않도록 설정 \r\n");
      out.write("     $(\"#mname\").blur(function() { \r\n");
      out.write("        if (nameJ.test($(this).val())) { \r\n");
      out.write("           console.log(nameJ.test($(this).val())); \r\n");
      out.write("           $(\"#name_check\").text(''); \r\n");
      out.write("        } else { \r\n");
      out.write("           $('#name_check').text('한글 2~4자 이내로 입력하세요. (특수기호, 공백 사용 불가)');\r\n");
      out.write("           $('#name_check').css('color', 'red'); \r\n");
      out.write("        } \r\n");
      out.write("     }); \r\n");
      out.write("          \r\n");
      out.write("     // 생일 유효성 검사 \r\n");
      out.write("     var birthJ = false; \r\n");
      out.write("     \r\n");
      out.write("     // 생년월일 birthJ 유효성 검사 \r\n");
      out.write("     $('#mbirth').blur(function(){ \r\n");
      out.write("        var dateStr = $(this).val(); \r\n");
      out.write("        var year = Number(dateStr.substr(0,4)); // 입력한 값의 0~4자리까지 (연) \r\n");
      out.write("        var month = Number(dateStr.substr(4,2)); // 입력한 값의 4번째 자리부터 2자리 숫자 (월) \r\n");
      out.write("        var day = Number(dateStr.substr(6,2)); // 입력한 값 6번째 자리부터 2자리 숫자 (일) \r\n");
      out.write("        var today = new Date(); // 날짜 변수 선언 \r\n");
      out.write("        var yearNow = today.getFullYear(); // 올해 연도 가져옴 \r\n");
      out.write("        \r\n");
      out.write("        if (dateStr.length <=8) { \r\n");
      out.write("           // 연도의 경우 1900 보다 작거나 yearNow 보다 크다면 false를 반환합니다. \r\n");
      out.write("           if (year > yearNow || year < 1900 ){ \r\n");
      out.write("              $('#birth_check').text('생년월일을 확인해주세요'); \r\n");
      out.write("              $('#birth_check').css('color', 'red'); \r\n");
      out.write("           } else if (month < 1 || month > 12) { \r\n");
      out.write("              $('#birth_check').text('생년월일을 확인해주세요 '); \r\n");
      out.write("              $('#birth_check').css('color', 'red'); \r\n");
      out.write("           } else if (day < 1 || day > 31) { \r\n");
      out.write("              $('#birth_check').text('생년월일을 확인해주세요 '); \r\n");
      out.write("              $('#birth_check').css('color', 'red'); \r\n");
      out.write("           } else if ((month==4 || month==6 || month==9 || month==11) && day==31) { \r\n");
      out.write("              $('#birth_check').text('생년월일을 확인해주세요 '); \r\n");
      out.write("              $('#birth_check').css('color', 'red'); \r\n");
      out.write("           } else if (month == 2) { \r\n");
      out.write("              var isleap = (year % 4 == 0 && (year % 100 != 0 || year % 400 == 0)); \r\n");
      out.write("              if (day>29 || (day==29 && !isleap)) { \r\n");
      out.write("                 $('#birth_check').text('생년월일을 확인해주세요 '); \r\n");
      out.write("                 $('#birth_check').css('color', 'red'); \r\n");
      out.write("              } else{ $('#birth_check').text(''); birthJ = true; \r\n");
      out.write("              } \r\n");
      out.write("           }else{ \r\n");
      out.write("              $('#birth_check').text(''); birthJ = true; \r\n");
      out.write("           }//end of if \r\n");
      out.write("        }else{ \r\n");
      out.write("           //1.입력된 생년월일이 8자 초과할때 : auth:false \r\n");
      out.write("           $('#birth_check').text('생년월일을 확인해주세요 '); \r\n");
      out.write("           $('#birth_check').css('color', 'red'); \r\n");
      out.write("        } \r\n");
      out.write("     }); //End of method /* \r\n");
      out.write("     \r\n");
      out.write("     // email check\r\n");
      out.write("     $(\"#memail\").blur(function() { \r\n");
      out.write("        if (emailJ.test($(this).val())) { \r\n");
      out.write("          console.log(nameJ.test($(this).val()));\r\n");
      out.write("           $(\"#email_check\").text(''); \r\n");
      out.write("        } else { \r\n");
      out.write("           $('#email_check').text('이메일 양식을 확인해주세요.'); \r\n");
      out.write("           $('#email_check').css('color', 'red'); \r\n");
      out.write("        } \r\n");
      out.write("     });    \r\n");
      out.write("     \r\n");
      out.write("     // 휴대전화 \r\n");
      out.write("     $('#mhp').blur(function(){ \r\n");
      out.write("        if(phoneJ.test($(this).val())){ \r\n");
      out.write("           console.log(nameJ.test($(this).val())); \r\n");
      out.write("           $(\"#phone_check\").text(''); \r\n");
      out.write("        } else { \r\n");
      out.write("           $('#phone_check').text('핸드폰번호를 확인해주세요 '); \r\n");
      out.write("           $('#phone_check').css('color', 'red'); \r\n");
      out.write("        } \r\n");
      out.write("     });  \r\n");
      out.write("     \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//우편번호 찾기 버튼 클릭시 발생 이벤트 \r\n");
      out.write("  function execPostCode() { \r\n");
      out.write("     new daum.Postcode({ \r\n");
      out.write("        oncomplete: function(data) { \r\n");
      out.write("           // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분. \r\n");
      out.write("           // 도로명 주소의 노출 규칙에 따라 주소를 조합한다. \r\n");
      out.write("           // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다. \r\n");
      out.write("           var fullRoadAddr = data.roadAddress; // 도로명 주소 변수 \r\n");
      out.write("           var extraRoadAddr = ''; // 도로명 조합형 주소 변수 \r\n");
      out.write("           \r\n");
      out.write("           // 법정동명이 있을 경우 추가한다. (법정리는 제외) \r\n");
      out.write("           // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다. \r\n");
      out.write("           if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){ \r\n");
      out.write("              extraRoadAddr += data.bname; \r\n");
      out.write("           } \r\n");
      out.write("           \r\n");
      out.write("           // 건물명이 있고, 공동주택일 경우 추가한다. \r\n");
      out.write("           if(data.buildingName !== '' && data.apartment === 'Y'){ \r\n");
      out.write("              extraRoadAddr += (extraRoadAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("           } \r\n");
      out.write("           \r\n");
      out.write("           // 도로명, 지번 조합형 주소가 있을 경우, 괄호까지 추가한 최종 문자열을 만든다. \r\n");
      out.write("           if(extraRoadAddr !== ''){ \r\n");
      out.write("              extraRoadAddr = ' (' + extraRoadAddr + ')'; \r\n");
      out.write("           } \r\n");
      out.write("           \r\n");
      out.write("           // 도로명, 지번 주소의 유무에 따라 해당 조합형 주소를 추가한다. \r\n");
      out.write("           if(fullRoadAddr !== ''){ \r\n");
      out.write("              fullRoadAddr += extraRoadAddr; \r\n");
      out.write("           } \r\n");
      out.write("           \r\n");
      out.write("           // 우편번호와 주소 정보를 해당 필드에 넣는다. \r\n");
      out.write("           console.log(data.zonecode); \r\n");
      out.write("           console.log(fullRoadAddr); \r\n");
      out.write("           /* \r\n");
      out.write("           var a = console.log(data.zonecode); \r\n");
      out.write("           var b = console.log(fullRoadAddr); \r\n");
      out.write("           if(a == null || b = null){\r\n");
      out.write("              alert(\"주소를 확인하세요.\"); return false; } \r\n");
      out.write("           */\r\n");
      out.write("           \r\n");
      out.write("           $(\"[name=mzipcode]\").val(data.zonecode); \r\n");
      out.write("           $(\"[name=maddr]\").val(fullRoadAddr); \r\n");
      out.write("           \r\n");
      out.write("           document.getElementById('mzipcode').value = data.zonecode; //5자리 새우편번호 사용 \r\n");
      out.write("           document.getElementById('maddr').value = fullRoadAddr; \r\n");
      out.write("           //document.getElementById('mem_detailaddress').value = data.jibunAddress; \r\n");
      out.write("        } \r\n");
      out.write("     }).open(); \r\n");
      out.write("  } \r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<!-- ***************************************************** 프롬 위치변경, 내용 일부 삭제-->\r\n");
      out.write("<form class=\"form-horizontal\" id=\"memForm\" name=\"memForm\">\r\n");
      out.write("<!-- ***************************************************** -->\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!--  -->\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t<section>      \r\n");
      out.write("        <h1 class=\"entry-title\"><span>Sign Up</span> </h1>\r\n");
      out.write("        <hr><!-- onsubmit=\"return submitCheck() -->\r\n");
      out.write("        \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("          \t<label class=\"control-label col-sm-3\">회원번호 <span class=\"text-danger\">*</span></label>\r\n");
      out.write("       \t\t<div class=\"col-md-8 col-sm-9\">\r\n");
      out.write("        \t\t<input type=\"text\" class=\"form-control\" name=\"mnum\" id=\"mnum\" placeholder=\"회원 번호\" readonly />\r\n");
      out.write("       \t\t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("          \t<label class=\"control-label col-sm-3\">이름 <span class=\"text-danger\">*</span></label>\r\n");
      out.write("          \t<div class=\"col-md-8 col-sm-9\">\r\n");
      out.write("            \t<input type=\"text\" class=\"form-control\" name=\"mname\" id=\"mname\" placeholder=\"이름\" />\r\n");
      out.write("            \t<div class=\"font\" id=\"name_check\"></div>            \t\r\n");
      out.write("          \t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("          \t<label class=\"control-label col-sm-3\">아이디 <span class=\"text-danger\">*</span></label>\r\n");
      out.write("          \t\r\n");
      out.write("          \t<div class=\"col-md-5 col-sm-5\">\r\n");
      out.write("            \t<input type=\"text\" class=\"form-control\" name=\"mid\" id=\"mid\" placeholder=\"아이디\" />\r\n");
      out.write("            \t<div class=\"font\" id=\"id_check\"></div>\r\n");
      out.write("          \t</div>\r\n");
      out.write("            <div class=\"col-md-4 col-sm-4\">\t\r\n");
      out.write("\t            <button type=\"button\" id=\"midbtn\" class=\"btn btn-info\" >중복 확인</button>\r\n");
      out.write("\t            <!-- <button type=\"button\" id=\"midbtnjson\">아이디체크(JSON)</button> -->\r\n");
      out.write("\t        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label class=\"control-label col-sm-3\">비밀번호 <span class=\"text-danger\">*</span></label>\r\n");
      out.write("\t\t\t<div class=\"col-md-8 col-sm-9\">\r\n");
      out.write("\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("              \t\t<span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-lock\"></i></span>\r\n");
      out.write("              \t\t<input type=\"password\" class=\"form-control\" name=\"mpw\" id=\"mpw\" placeholder=\"비밀번호\" />\r\n");
      out.write("           \t  \t\t<div class=\"font\" id=\"pw_check\"></div>\r\n");
      out.write("           \t\t</div>\r\n");
      out.write("          \t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label class=\"control-label col-sm-3\">비밀번호 확인 <span class=\"text-danger\">*</span></label>\r\n");
      out.write("\t\t\t<div class=\"col-md-8 col-sm-9\">\r\n");
      out.write("            \t<div class=\"input-group\">\r\n");
      out.write("              \t\t<span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-lock\"></i></span>\r\n");
      out.write("              \t\t<input type=\"password\" class=\"form-control\" name=\"mpw2\" id=\"mpw2\" placeholder=\"비밀번호 확인\" />\r\n");
      out.write("            \t\t<div class=\"font\" id=\"pw2_check\"></div>\r\n");
      out.write("            \t</div>\r\n");
      out.write("          \t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label class=\"control-label col-sm-3\">생년월일 <span class=\"text-danger\">*</span></label>\r\n");
      out.write("\t\t\t<div class=\"col-md-8 col-sm-9\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"mbirth\" id=\"mbirth\" placeholder=\"예:19940121\" />\r\n");
      out.write("\t\t\t\t<div class=\"font\" id=\"birth_check\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("          \t<label class=\"control-label col-sm-3\">성별 <span class=\"text-danger\">*</span></label>\r\n");
      out.write("          \t<div class=\"col-md-8 col-sm-9\">\r\n");
      out.write("            \t<label><input name=\"mgender\" id=\"mgender\" type=\"radio\" value=\"M\" checked>남 </label>\r\n");
      out.write("            \t<label><input name=\"mgender\" id=\"mgender\" type=\"radio\" value=\"F\" >여 </label>\r\n");
      out.write("          \t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("\t\t\t<label class=\"control-label col-sm-3\">핸드폰번호 <span class=\"text-danger\">*</span><br>\r\n");
      out.write("\t\t\t<small>('-' 없이 번호만 입력)</small></label>\r\n");
      out.write(" \t\t\t<div class=\"col-md-8 col-sm-9\">\r\n");
      out.write("            \t<input type=\"text\" class=\"form-control\" name=\"mhp\" id=\"mhp\" placeholder=\"예:01055557777\" />\r\n");
      out.write("            \t<div class=\"font\" id=\"phone_check\"></div>\r\n");
      out.write("          \t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label class=\"control-label col-sm-3\">이메일 <span class=\"text-danger\">*</span></label>\r\n");
      out.write("          \t<div class=\"col-md-5 col-sm-5\">\r\n");
      out.write("\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t              \t<span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-envelope\"></i></span>\r\n");
      out.write("\t              \t<input type=\"email\" class=\"form-control\" name=\"memail\" id=\"memail\" placeholder=\"sunny@example.com\" /> \r\n");
      out.write("              \t</div>\r\n");
      out.write("          \t</div>\r\n");
      out.write("          \t\r\n");
      out.write("    <!--       \t<input type=\"text\" placeholder=\"E-Mail\" name=\"memail\" id=\"memail\">@ \r\n");
      out.write("    \t\t\t<select name=\"domain\" id=\"domain\">\r\n");
      out.write("\t\t\t\t\t<option value=\"gmail.com\">gmail.com</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"naver.com\">naver.com</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"daum.net\">daum.net</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"yahoo.co.kr\">yahoo.co.kr</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t  -->\r\n");
      out.write("          \t\r\n");
      out.write("            <div class=\"col-md-4 col-sm-4\">\t\r\n");
      out.write("\t            <button type=\"button\" id=\"memailbtn\" class=\"btn btn-default\" >인증 코드 발송</button>\r\n");
      out.write("\t        </div>          \t\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("\t\t\t<label class=\"control-label col-sm-3\"></label>\r\n");
      out.write("          \t<div class=\"col-md-5 col-sm-5\">\r\n");
      out.write("\t              \t<input type=\"text\" class=\"form-control\" name=\"emcode\" id=\"emcode\" placeholder=\"인증코드\" /> \r\n");
      out.write("\t              \t<div class=\"font\" id=\"code_check\"></div>\r\n");
      out.write("          \t</div>          \t\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("\t\t\t<label class=\"control-label col-sm-3\">주소 <span class=\"text-danger\">*</span></label>        \r\n");
      out.write("\t\t\t<div class=\"col-md-5 col-sm-5\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"mzipcode\" id=\"mzipcode\" placeholder=\"우편번호\" readonly />\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4 col-sm-4\">\t\r\n");
      out.write("\t            <button type=\"button\" id=\"memaddr\" class=\"btn btn-default\" onclick=\"execPostCode();\">우편번호 찾기</button>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label class=\"control-label col-sm-3\"><span class=\"text-danger\"></span></label>\r\n");
      out.write("          \t<div class=\"col-md-8 col-sm-9\">\r\n");
      out.write("\t            \t<input type=\"text\" class=\"form-control\" name=\"maddr\" id=\"maddr\" placeholder=\"도로명 주소\" readonly/>\r\n");
      out.write("            </div> \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label class=\"control-label col-sm-3\"><span class=\"text-danger\"></span></label>\r\n");
      out.write("          \t<div class=\"col-md-8 col-sm-9\">\r\n");
      out.write("\t            \t<input type=\"text\" class=\"form-control\" name=\"maddrdetail\" id=\"maddrdetail\" placeholder=\"상세주소\" />\t\r\n");
      out.write("            </div> \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("          <div class=\"col-xs-offset-5 col-xs-10\">\r\n");
      out.write("          <!-- *************************************** 회가입 id=추가, type=변경 --> \r\n");
      out.write("            <input name=\"Submit\" type=\"button\" id=\"submitBtn\" value=\"회원 가입\" class=\"btn btn-primary btn-lg\">\r\n");
      out.write("          <!--****************************************-->\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      \r\n");
      out.write("      </section>\r\n");
      out.write("    </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</form>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
