/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.60
 * Generated at: 2021-03-10 09:57:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import g.g.d.com.mem.vo.MemberVO;
import g.g.d.com.mem.common.TempPassword;

public final class memberSelect_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("g.g.d.com.mem.vo.MemberVO");
    _jspx_imports_classes.add("g.g.d.com.mem.common.TempPassword");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<!-- 디바이스에 최적화된 크기로 출력됨 -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\r\n");
      out.write("      maximum-scale=1.0, minimum-scale=1.0, user-scalable=no\">\r\n");
      out.write("<!-- 추가 -->\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/include/css/main.css\" />\r\n");
      out.write("\r\n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("<script src=\"//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<!------ Include the above in your HEAD tag ---------->\r\n");
      out.write("<title>회원 정보 상세 페이지</title>\r\n");
      out.write("\r\n");
      out.write("<!-- daum 도로명주소 찾기 api -->\r\n");
      out.write("<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");

String mnum=request.getAttribute("mnum").toString();
//System.out.println("====================================="+mnum);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t\r\n");
      out.write("\t// 비밀번호 확인 시작-----------------------------------------------------------\r\n");
      out.write("\t$(document).on(\"click\", \"#mpwbtn\", function(){\r\n");
      out.write("\t\tconsole.log(\"midbtn >>> : \");\r\n");
      out.write("\t\t//alert(\"mpwbtn >>> : \");\r\n");
      out.write("\r\n");
      out.write("\t\tlet pwcheckURL = \"pwCheck.ggd\"\r\n");
      out.write("\t\tlet method = \"POST\";\r\n");
      out.write("\t\tlet dataParam = {\r\n");
      out.write("\t\t\tmnum: $(\"#mnum\").val(),\r\n");
      out.write("\t\t\tmpw: $(\"#mpw\").val(),\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t//dataParam = $(\"#boardUpdateForm\").serialize();\r\n");
      out.write("\t\t//alert(\"dataParam >>> : \" + dataParam);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: pwcheckURL,\r\n");
      out.write("\t\t\ttype: method, // 요청 ContentType\r\n");
      out.write("\t\t\tdata: dataParam,\r\n");
      out.write("            // contentType: \"application/json;\",\r\n");
      out.write("            // dataType: \"json\", // 응답 ContentType\r\n");
      out.write("\t\t\tsuccess: whenSuccess,\r\n");
      out.write("\t\t\terror: whenError\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction whenSuccess(resData){\r\n");
      out.write("\t\t\t//alert(\"resData >>> : \" + resData);\r\n");
      out.write("\t\t\tconsole.log(resData);\r\n");
      out.write("\t\t\tvar sVal = resData;\r\n");
      out.write("\t\t\tif (resData){\r\n");
      out.write("\t\t\t\t//$('#mpw').attr('disabled', true); // attr(), 1.6 이후 사용 prop()\r\n");
      out.write("\t\t\t\t$('#mpwbtn').attr('style', 'visibility:hidden');\r\n");
      out.write("\t\t\t\t$('#mpw').val();\r\n");
      out.write("\t\t\t\t$('#mpw').focus();\r\n");
      out.write("\t\t\t\t$('#pwC2').attr('style', 'display:show');\r\n");
      out.write("\t\t\t\t$('#btnUpdate').attr('disabled', false);\r\n");
      out.write("\t\t\t\t$('#btnDelete').attr('disabled', false);\r\n");
      out.write("\t\t\t\t//$('#btnUpdate').css('background-color', 'red');\r\n");
      out.write("\t\t\t\t//$('#btnDelete').css('color', 'red');\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$('#mpw').val('');\r\n");
      out.write("\t\t\t\t$('#mpw').focus();\r\n");
      out.write("\t\t\t\t$('#btnUpdate').attr('disabled', true);\r\n");
      out.write("\t\t\t\t$('#btnDelete').attr('disabled', true);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction whenError(e){\r\n");
      out.write("\t\t\t//alert(\"e >>> : \" + e.responseText);\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t// 비밀번호 확인 끝-----------------------------------------------------------\r\n");
      out.write("\t\r\n");
      out.write("\t// 인증코드 발송  시작-----------------------------------------------------------\r\n");
      out.write("\tvar isCertification = false;\r\n");
      out.write("\tvar key = '");
      out.print(TempPassword.setTempPassWord(10));
      out.write("';\r\n");
      out.write("\t$(\"#memailbtn\").click(function() {// 메일 입력 유효성 검사\r\n");
      out.write("\t\tvar mail = $(\"#memail\").val(); // 사용자의 이메일 입력값.\r\n");
      out.write("\t\tif (mail == \"\") {\r\n");
      out.write("\t\t\talert(\"메일 주소가 입력되지 않았습니다.\");\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t//alert(mail);\r\n");
      out.write("\t\t\t//returnGetData(meail);\r\n");
      out.write("\t\t\t//mail = mail + \"@\" + $(\".domain\").val(); // 셀렉트 박스에 @뒤 값들을 더함.\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype : 'get',\r\n");
      out.write("\t\t\t\turl : 'mailCheck.ggd',\r\n");
      out.write("\t\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\t\tasync : \"false\",\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\"mail\" : mail,\r\n");
      out.write("\t\t\t\t\t\"key\" : key\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t//alert(data);\r\n");
      out.write("\t\t\t\t\t//console.log(data);\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\t\t\t\r\n");
      out.write("\t\t\talert(\"인증코드를 발송하였습니다.\\n이메일을 확인하시기 바랍니다.\");\r\n");
      out.write("\t\t\t$(\"#emcode\").css(\"display\", \"block\");\r\n");
      out.write("\t\t\t$(\"#code_check\").css(\"display\", \"block\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//alert(key);\r\n");
      out.write("\t});\r\n");
      out.write("\tasync function returnGetData(email){\r\n");
      out.write("\t\tlet data='';\r\n");
      out.write("\t\tdata=await emaulCon(email);\r\n");
      out.write("\t\t//alert(data);\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction emaulCon(email){\r\n");
      out.write("\t\tvar sendURL=\"\";\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t// -----인증 키 일치여부 확인 ---------------------------------------------------\r\n");
      out.write("\t$(\"#emcode\").on(\"propertychange change keyup paste input\", function() {\r\n");
      out.write("\t\t//alert(\"key>>>\"+key);\r\n");
      out.write("\t\tif ($(\"#emcode\").val() == key) {\r\n");
      out.write("\t\t\t$(\"#code_check\").text(\"인증 완료!\").css(\"color\", \"black\");\r\n");
      out.write("  \t\t\tisCertification = true;\r\n");
      out.write("  \t\t} else {\r\n");
      out.write("  \t\t\t$(\"#code_check\").text(\"다시 확인하여 주시기 바랍니다.\").css(\"color\", \"red\");\r\n");
      out.write("  \t\t\tisCertification = false;\r\n");
      out.write("  \t\t}\r\n");
      out.write("  \t});\r\n");
      out.write("\t// 인증코드 발송  끝-----------------------------------------------------------\r\n");
      out.write("\t\r\n");
      out.write("\t//1~2 패스워드 일치 확인 \r\n");
      out.write("     $('#mpw2').blur(function() { \r\n");
      out.write("        if ($('#mpw').val() != $(this).val()) { \r\n");
      out.write("           $('#pw2_check').text('비밀번호가 일치하지 않습니다.'); \r\n");
      out.write("           $('#pw2_check').css('color', 'red'); \r\n");
      out.write("        } else { $('#pw2_check').text(''); \r\n");
      out.write("       \t} \r\n");
      out.write("     }); \r\n");
      out.write("     \r\n");
      out.write("\t\r\n");
      out.write("\t//  U\r\n");
      out.write("\t$(document).on(\"click\", \"#btnUpdate\", function(){\r\n");
      out.write("\t\t//확인 대화상자\r\n");
      out.write("\t\tif($('#mpw2').val().length>1){\r\n");
      out.write("\t\t\tif($('#mpw').val()==$('#mpw2').val()){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tif(confirm(\"수정하시겠습니까?\")){\r\n");
      out.write("\t\t\t\t\t//document.form1.action = \"gogodaProject/memberUpdate.ggd\";\r\n");
      out.write("\t\t\t\t\t//document.form1.submit();\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\ttype : 'POST',\r\n");
      out.write("\t\t\t\t\t\turl : 'memberUpdate.ggd',\r\n");
      out.write("\t\t\t\t\t\tdataType : 'text',\r\n");
      out.write("\t\t\t\t\t\tasync : false,\r\n");
      out.write("\t\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\t\"mnum\":$('#mnum').val(),\r\n");
      out.write("\t\t\t\t\t\t\t\"mname\":$('#mname').val(),\r\n");
      out.write("\t\t\t    \t\t\t\"mid\":$('#mid').val(),\r\n");
      out.write("\t\t\t    \t\t\t\"mpw\":$('#mpw').val(),\r\n");
      out.write("\t\t\t    \t\t\t\"mbirth\":$('#mbirth').val(),\r\n");
      out.write("\t\t\t    \t\t\t\"mgender\":$('#mgender').val(),\r\n");
      out.write("\t\t\t    \t\t\t\"mhp\":$('#mhp').val(),\r\n");
      out.write("\t\t\t    \t\t\t\"memail\":$('#memail').val(),\r\n");
      out.write("\t\t\t    \t\t\t\"mzipcode\":$('#mzipcode').val(),\r\n");
      out.write("\t\t\t    \t\t\t\"maddr\":$('#maddr').val(),\r\n");
      out.write("\t\t\t    \t\t\t\"maddrdetail\":$('#maddrdetail').val()\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\tsuccess : whenSuccess,\r\n");
      out.write("\t\t\t\t\t\terror : whenError});\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t    \t\tfunction whenSuccess(data) {\r\n");
      out.write("\t\t\t\t\t\t\talert(\"다시 로그인해주세요\");\r\n");
      out.write("\t\t\t\t\t\t\tlocation.href=\"../../../../../emotion/logout.ggd\";\r\n");
      out.write("\t\t\t    \t\t}\r\n");
      out.write("\t\t\t    \t\tfunction whenError(){\r\n");
      out.write("\t\t\t    \t\t\t\r\n");
      out.write("\t\t\t    \t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}else{alert(\"비밀번호가 일치하지 않습니다.\");}\r\n");
      out.write("\t\t}else{alert(\"비밀번호가 일치하지 않습니다.\");}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//  D\r\n");
      out.write("\t$(document).on(\"click\", \"#btnDelete\", function(){\r\n");
      out.write("\t\t// 확인 대화상자\t\r\n");
      out.write("\t\tif(confirm(\"삭제하시겠습니까?\")){\r\n");
      out.write("\t\t\t//document.form1.action = \"/gogodaProject/memberDelete.ggd\";\r\n");
      out.write("\t\t\t//document.form1.submit();\r\n");
      out.write("\t\t\t$(\"#memberUpdateForm\").attr({ \"method\":\"POST\",\"action\":\"memberDelete.ggd\"}).submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//------ 우편번호 찾기  블럭  시작 -----------------------------------------------\r\n");
      out.write("function execPostCode() { \r\n");
      out.write("\tnew daum.Postcode({ \r\n");
      out.write("\t\toncomplete: function(data) { \r\n");
      out.write("\t\t\t// 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분. \r\n");
      out.write("\t\t\t// 도로명 주소의 노출 규칙에 따라 주소를 조합한다. \r\n");
      out.write("\t\t\t// 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다. \r\n");
      out.write("\t\t\tvar fullRoadAddr = data.roadAddress; // 도로명 주소 변수 \r\n");
      out.write("\t\t\tvar extraRoadAddr = ''; // 도로명 조합형 주소 변수 \r\n");
      out.write("\t\t\t           \r\n");
      out.write("\t\t\t// 법정동명이 있을 경우 추가한다. (법정리는 제외) \r\n");
      out.write("\t\t\t// 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다. \r\n");
      out.write("\t\t\tif(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){ \r\n");
      out.write("\t\t\t   extraRoadAddr += data.bname; \r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t\t           \r\n");
      out.write("\t\t\t// 건물명이 있고, 공동주택일 경우 추가한다. \r\n");
      out.write("\t\t\tif(data.buildingName !== '' && data.apartment === 'Y'){ \r\n");
      out.write("\t\t\t   extraRoadAddr += (extraRoadAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t\t           \r\n");
      out.write("\t\t\t// 도로명, 지번 조합형 주소가 있을 경우, 괄호까지 추가한 최종 문자열을 만든다. \r\n");
      out.write("\t\t\tif(extraRoadAddr !== ''){ \r\n");
      out.write("\t\t\t   extraRoadAddr = ' (' + extraRoadAddr + ')'; \r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t\t           \r\n");
      out.write("\t\t\t// 도로명, 지번 주소의 유무에 따라 해당 조합형 주소를 추가한다. \r\n");
      out.write("\t\t\tif(fullRoadAddr !== ''){ \r\n");
      out.write("\t\t\t   fullRoadAddr += extraRoadAddr; \r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t\t           \r\n");
      out.write("\t\t\t// 우편번호와 주소 정보를 해당 필드에 넣는다. \r\n");
      out.write("\t\t\tconsole.log(data.zonecode); \r\n");
      out.write("\t\t\tconsole.log(fullRoadAddr); \r\n");
      out.write("\t\t\t/* \r\n");
      out.write("\t\t\tvar a = console.log(data.zonecode); \r\n");
      out.write("\t\t\tvar b = console.log(fullRoadAddr); \r\n");
      out.write("\t\t\tif(a == null || b = null){\r\n");
      out.write("\t\t\t   alert(\"주소를 확인하세요.\"); return false; } \r\n");
      out.write("\t\t\t*/\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"[name=mzipcode]\").val(data.zonecode); \r\n");
      out.write("\t\t\t$(\"[name=maddr]\").val(fullRoadAddr); \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tdocument.getElementById('mzipcode').value = data.zonecode; //5자리 새우편번호 사용 \r\n");
      out.write("\t\t\tdocument.getElementById('maddr').value = fullRoadAddr; \r\n");
      out.write("\t\t\t//document.getElementById('mem_detailaddress').value = data.jibunAddress; \r\n");
      out.write("\t\t} \r\n");
      out.write("\t}).open(); \t\r\n");
      out.write("}\r\n");
      out.write("// ------ 우편번호 찾기 발송  블럭 끝      -----------------------------------------------\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<!-- ***************************************************** 프롬 위치변경, 내용 일부 삭제-->\r\n");
      out.write("<form class=\"form-horizontal\" id=\"memberUpdateForm\" name=\"memberUpdateForm\">\r\n");
      out.write("<!-- ***************************************************** -->\r\n");
      out.write("<body>\r\n");
      out.write("<!--  -->\r\n");
      out.write("\r\n");
      out.write("<!-- Navbar (sit on top) -->\r\n");
      out.write("<div class=\"w3-top\">\r\n");
      out.write("\t<div class=\"w3-bar w3-white w3-wide w3-padding w3-card\">\r\n");
      out.write("\t\t<a href=\"../../emotion/mainpage.ggd\">\r\n");
      out.write("\t\t\t<img src=\"/logo/GOGODA-logo.png\" style=\"width:12%; height:12%\">\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div><br><br><br><br><br><br><br>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t<section>      \r\n");
      out.write("        <h1 class=\"entry-title\"><span><b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.mname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b>님의 상세 정보</span> </h1>\r\n");
      out.write("        <hr>\r\n");
      out.write("\t\t\t<input type=\"hidden\" class=\"form-control\" name=\"mnum\" id=\"mnum\" value='");
      out.print(mnum);
      out.write("' readonly />\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("          \t<label class=\"control-label col-sm-3\">이름 <span class=\"text-danger\">*</span></label>\r\n");
      out.write("          \t<div class=\"col-md-8 col-sm-9\">\r\n");
      out.write("            \t<input type=\"text\" class=\"form-control\" name=\"mname\" id=\"mname\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.mname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly />        \t\r\n");
      out.write("          \t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("          \t<label class=\"control-label col-sm-3\">아이디 <span class=\"text-danger\">*</span></label>\r\n");
      out.write("          \t<div class=\"col-md-8 col-sm-9\">\r\n");
      out.write("            \t<input type=\"text\" class=\"form-control\" name=\"mid\" id=\"mid\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.mid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly />\r\n");
      out.write("          \t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("          \t<label class=\"control-label col-sm-3\">비밀번호 <span class=\"text-danger\">*</span></label>\r\n");
      out.write("          \t\r\n");
      out.write("          \t<div class=\"col-md-5 col-sm-5\">\r\n");
      out.write("            \t<div class=\"input-group\">\r\n");
      out.write("              \t\t<span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-lock\"></i></span>\r\n");
      out.write("              \t\t<input type=\"password\" class=\"form-control\" name=\"mpw\" id=\"mpw\" placeholder=\"비밀번호\" />\r\n");
      out.write("          \t\t</div>\r\n");
      out.write("          \t</div>\r\n");
      out.write("            <div class=\"col-md-4 col-sm-4\">\t\r\n");
      out.write("\t            <button type=\"button\" id=\"mpwbtn\" class=\"btn btn-info\" >비밀번호 확인</button>\r\n");
      out.write("\t        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"form-group\" id=\"pwC2\" style=\"display:none;\">\r\n");
      out.write("\t\t\t<label class=\"control-label col-sm-3\">비밀번호 확인 <span class=\"text-danger\">*</span></label>\r\n");
      out.write("\t\t\t<div class=\"col-md-5 col-sm-5\">\r\n");
      out.write("            \t<div class=\"input-group\">\r\n");
      out.write("              \t\t<span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-lock\"></i></span>\r\n");
      out.write("              \t\t<input type=\"password\" class=\"form-control\" name=\"mpw2\" id=\"mpw2\" placeholder=\"비밀번호 확인\" />\r\n");
      out.write("            \t\t<div class=\"font\" id=\"pw2_check\"></div>\r\n");
      out.write("            \t</div>\r\n");
      out.write("          \t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label class=\"control-label col-sm-3\">생년월일 <span class=\"text-danger\">*</span></label>\r\n");
      out.write("\t\t\t<div class=\"col-md-8 col-sm-9\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"mbirth\" id=\"mbirth\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.mbirth}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("          \t<label class=\"control-label col-sm-3\">성별 <span class=\"text-danger\">*</span></label>\r\n");
      out.write("          \t<div class=\"col-md-8 col-sm-9\">\r\n");
      out.write("            \t<input type=\"text\" class=\"form-control\" name=\"mgender\" id=\"mgender\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.mgender}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("          \t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("\t\t\t<label class=\"control-label col-sm-3\">핸드폰번호 <span class=\"text-danger\">*</span><br>\r\n");
      out.write("\t\t\t<small>('-' 없이 번호만 입력)</small></label>\r\n");
      out.write(" \t\t\t<div class=\"col-md-8 col-sm-9\">\r\n");
      out.write("            \t<input type=\"text\" class=\"form-control\" name=\"mhp\" id=\"mhp\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.mhp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("          \t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label class=\"control-label col-sm-3\">이메일 <span class=\"text-danger\">*</span></label>\r\n");
      out.write("          \t<div class=\"col-md-5 col-sm-5\">\r\n");
      out.write("\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t              \t<span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-envelope\"></i></span>\r\n");
      out.write("\t              \t<input type=\"email\" class=\"form-control\" name=\"memail\" id=\"memail\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.memail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /> \r\n");
      out.write("              \t</div>\r\n");
      out.write("          \t</div>\r\n");
      out.write("    <!--       \t<input type=\"text\" placeholder=\"E-Mail\" name=\"memail\" id=\"memail\">@ \r\n");
      out.write("    \t\t\t<select name=\"domain\" id=\"domain\">\r\n");
      out.write("\t\t\t\t\t<option value=\"gmail.com\">gmail.com</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"naver.com\">naver.com</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"daum.net\">daum.net</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"yahoo.co.kr\">yahoo.co.kr</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t  -->\r\n");
      out.write("            <div class=\"col-md-4 col-sm-4\">\t\r\n");
      out.write("\t            <button type=\"button\" id=\"memailbtn\" class=\"btn btn-default\" >인증 코드 발송</button>\r\n");
      out.write("\t        </div>          \t\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("\t\t\t<label class=\"control-label col-sm-3\"></label>\r\n");
      out.write("          \t<div class=\"col-md-5 col-sm-5\">\r\n");
      out.write("\t        \t<input type=\"text\" class=\"form-control\" name=\"emcode\" id=\"emcode\" placeholder=\"인증코드\" /> \r\n");
      out.write("\t        \t<div class=\"font\" id=\"code_check\"></div>\r\n");
      out.write("          \t</div>          \t\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("\t\t\t<label class=\"control-label col-sm-3\">주소 <span class=\"text-danger\">*</span></label>        \r\n");
      out.write("\t\t\t<div class=\"col-md-5 col-sm-5\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"mzipcode\" id=\"mzipcode\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.mzipcode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly />\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4 col-sm-4\">\t\r\n");
      out.write("\t            <button type=\"button\" id=\"memaddr\" class=\"btn btn-default\" onclick=\"execPostCode();\">우편번호 찾기</button>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label class=\"control-label col-sm-3\"><span class=\"text-danger\"></span></label>\r\n");
      out.write("          \t<div class=\"col-md-8 col-sm-9\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"maddr\" id=\"maddr\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.maddr}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly/>\r\n");
      out.write("            </div> \r\n");
      out.write("        </div>\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label class=\"control-label col-sm-3\"><span class=\"text-danger\"></span></label>\r\n");
      out.write("          \t<div class=\"col-md-8 col-sm-9\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"maddrdetail\" id=\"maddrdetail\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.maddrdetail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\t\r\n");
      out.write("            </div> \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("          \t<label class=\"control-label col-sm-3\">회원 가입일</label>\r\n");
      out.write("          \t<div class=\"col-md-8 col-sm-9\">\r\n");
      out.write("            \t<input type=\"text\" class=\"form-control\" name=\"minsertdate\" id=\"minsertdate\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.minsertdate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"  readonly />\r\n");
      out.write("          \t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("          \t<label class=\"control-label col-sm-3\">회원정보 수정일</label> \t\r\n");
      out.write("          \t<div class=\"col-md-8 col-sm-9\">\r\n");
      out.write("            \t<input type=\"text\" class=\"form-control\" name=\"mupdatedate\" id=\"mupdatedate\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.mupdatedate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly />\r\n");
      out.write("          \t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("          <div class=\"col-md-offset-5 col-xs-offset-5\">\r\n");
      out.write("            <input type=\"button\" name=\"btnUpdate\" id=\"btnUpdate\" value=\"수정\" class=\"btn btn-primary btn-lg\" disabled=\"disabled\">        \r\n");
      out.write("            <input type=\"button\" name=\"btnDelete\" id=\"btnDelete\" value=\"삭제\" class=\"btn btn-danger btn-lg\" disabled=\"disabled\">\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </section>\r\n");
      out.write("     </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<footer class=\"w3-center w3-black w3-padding-16\">\r\n");
      out.write("  <p>Powered by&nbsp;<a href=\"../../emotion/mainpage.ggd\" title=\"GOGODA\" target=\"_blank\" class=\"w3-hover-text-green\"><b>GOGODA</b></a></p>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</form>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
