/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.60
 * Generated at: 2021-03-10 08:29:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mainlogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

 String mid = ""; 
 String mname = ""; 
 String mpw = ""; 
 String memail = ""; 
	HttpSession hs = null; 
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1610932211247L));
    _jspx_dependants.put("jar:file:/C:/00.KOSMO72/eclipse_springproject_work/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/springProject/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\t    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("<title>Login_Form</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/include/css/main.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/include/css/login.css\" />\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).on(\"click\",\"#login_btn\",function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar id = $(\"#mid\").val();\r\n");
      out.write("\t\tvar pw = $(\"#mpw\").val();\r\n");
      out.write("\t\t//alert(\"로그인 버튼 누름~\" + id + \"==\" + pw);\r\n");
      out.write("\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"loginresult.ggd\",\r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\tasync : false,\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\"mid\" : id,\r\n");
      out.write("\t\t\t\t\"mpw\" : pw\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType : 'text',\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t//alert(data);\r\n");
      out.write("\t\t\t\tconsole.log(\"data : \" + data);\r\n");
      out.write("\t\t\t\tif (data == \"login_ok\") {\r\n");
      out.write("\t\t\t\t\talert(\"로그인 성공. 메인페이지로 이동\");\r\n");
      out.write("\t\t\t\t\t$(\"#loginForm\").attr(\"action\",\"../emotion/login.ggd\");\r\n");
      out.write("\t\t\t\t\t$(\"#loginForm\").attr(\"method\",\"POST\");\r\n");
      out.write("\t\t\t\t\t$(\"#loginForm\").attr(\"enctype\",\"application/x-www-form-urlencoded\");\r\n");
      out.write("\t\t\t\t\t$(\"#loginForm\").submit();\r\n");
      out.write("\t\t\t\t} else if (data == \"not_find_id\") {\r\n");
      out.write("\t\t\t\t\talert(\"일치하는 아이디가 없습니다. 다시 입력해주세요.\");\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t} else{\r\n");
      out.write("\t\t\t\t\t//alert(data);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(data) {\r\n");
      out.write("\t\t\t\tconsole.log(\"에러발생\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Navbar (sit on top) -->\r\n");
      out.write("<div class=\"w3-top\">\r\n");
      out.write("\t<div class=\"w3-bar w3-white w3-wide w3-padding w3-card\">\r\n");
      out.write("\t\t<a href=\"../../emotion/mainpage.ggd\">\r\n");
      out.write("\t\t\t<img src=\"/logo/GOGODA-logo.png\" style=\"width:15%; height:15%\">\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\t<form name=\"loginForm\" id=\"loginForm\">\r\n");
      out.write("\t\t<div class=\"box\">\r\n");
      out.write("\t\t\t<h1>Log in</h1><br>\r\n");
      out.write("\t\t\t\t<div class=\"inputBox\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"mid\" id=\"mid\" required onkeyup=\"this.setAttribute('value', this.value);\"  value=\"\">\r\n");
      out.write("\t\t\t\t\t<label>ID</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"inputBox\">\r\n");
      out.write("\t\t\t\t\t<input type=\"password\" name=\"mpw\" id=\"mpw\" required onkeyup=\"this.setAttribute('value', this.value);\" value=\"\">\r\n");
      out.write("\t\t\t\t\t<label>Password</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<!-- 네이버 로그인 창으로 이동 -->\r\n");
      out.write("\t\t\t<div id=\"naver_id_login\" style=\"text-align:left\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t<img width=\"190\" src=\"https://developers.naver.com/doc/review_201802/CK_bEFnWMeEBjXpQ5o8N_20180202_7aot50.png\"/></a>\r\n");
      out.write("\t\t\t<input type=\"submit\" name=\"login_btn\" id=\"login_btn\" value=\"Log In\" style=\"text-align:right; margin-right:17px\"><br><br><br></div>\r\n");
      out.write("\t\t\t<div class=\"link_look\">\r\n");
      out.write("\t\t\t\t<a href=\"idFind.ggd\">아이디 찾기</a>&nbsp;\r\n");
      out.write("\t\t\t\t<a href=\"pwFind.ggd\">비밀번호  찾기</a>&nbsp;\r\n");
      out.write("\t\t\t\t<a href=\"../../mem/registerForm.ggd\" id=\"memberhover\">회원가입</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
