/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.60
 * Generated at: 2021-03-05 09:17:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/C:/00.KOSMO72/eclipse_springproject_work/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/springProject/WEB-INF/lib/standard.jar!/META-INF/fn.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1610932211247L));
    _jspx_dependants.put("jar:file:/C:/00.KOSMO72/eclipse_springproject_work/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/springProject/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/C:/00.KOSMO72/eclipse_springproject_work/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/springProject/WEB-INF/lib/spring-webmvc-4.3.16.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1523252374000L));
    _jspx_dependants.put("/WEB-INF/tld/custom_tag.tld", Long.valueOf(1614243621373L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.16.RELEASE.jar", Long.valueOf(1609528656000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<!-- 디바이스에 최적화된 크기로 출력됨 -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\r\n");
      out.write("      maximum-scale=1.0, minimum-scale=1.0, user-scalable=no\">\r\n");
      out.write("<title>GOGODA HOMEPAGE</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/include/css/main.css\" />\r\n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<script  src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\tvar boardData;\r\n");
      out.write("\t\t//alert(\"ready\");\r\n");
      out.write("\t\t$(window).load(function(){\r\n");
      out.write("\t\t\tif(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${seName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"!=''){\r\n");
      out.write("\t\t\t\t$(\"#loginbtn\").remove();\r\n");
      out.write("\t\t\t\t$(\"#meminsert\").remove();\r\n");
      out.write("\t\t\t\t$(\"#memlogin\").append(\"<a href='../../springProject/mem/memberSelect.ggd' style='color:black' id='' class='comlogin'>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${seName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>님 환영합니다. &nbsp;&nbsp;&nbsp;\");\r\n");
      out.write("\t\t\t\t$(\"#memlogin\").append(\"<button type='button' class='comlogin' id='memlogout' onclick='logoutBtn()'>로그아웃</button>\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t//게시판 최신순 조회\r\n");
      out.write("\t\t\t $.ajax({\r\n");
      out.write("\t                url : '../../springProject/emotion/mainboard.ggd',\r\n");
      out.write("\t                type : 'POST',\r\n");
      out.write("\t                async:false,\r\n");
      out.write("\t                datatype:'json',\r\n");
      out.write("\t                success: function(data) {\r\n");
      out.write("\t                \tboardData=data;\r\n");
      out.write("\t                \tfor(var i=0;i<boardData.length;i++){\r\n");
      out.write("\t                \t\tif(boardData[i][\"bsubject\"].length<35){\r\n");
      out.write("\t\t\t                \tvar boardListData=\"<li>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"<a href='../../springProject/board/boardDetail.ggd?bnum=\"+boardData[i][\"bnum\"]+\"' style='color:black;' id='a-none'>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"<span><b>\"+boardData[i][\"bname\"]+\"</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\"+\r\n");
      out.write("\t\t\t\t\t\t\t\tboardData[i][\"bsubject\"]+\"<font color='#1551a4'>[\"+boardData[i][\"cnt\"]+\"]</font></a>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"</li><br>\";\r\n");
      out.write("\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\tvar boardListData=\"<li>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"<a href='../../springProject/board/boardDetail.ggd?bnum=\"+boardData[i][\"bnum\"]+\"' style='color:black;' id='a-none'>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"<span><b>\"+boardData[i][\"bname\"]+\"</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\"+\r\n");
      out.write("\t\t\t\t\t\t\t\tboardData[i][\"bsubject\"].substring(0,35)+\"<font color='#1551a4'>[\"+boardData[i][\"cnt\"]+\"]</font></a>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"</li><br>\";\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t                \t$(\"#boardlist-main\").append(boardListData);\r\n");
      out.write("\t                \t}\r\n");
      out.write("\t                },\r\n");
      out.write("\t                error: function(){}\t\t\t\r\n");
      out.write("\t\t\t });\r\n");
      out.write("\t\t\t //음식 랭킹 조회\r\n");
      out.write("\t\t\t $.ajax({\r\n");
      out.write("\t                url : '../../springProject/emotion/foodrank.ggd',\r\n");
      out.write("\t                type : 'POST',\r\n");
      out.write("\t                async:false,\r\n");
      out.write("\t                datatype:'json',\r\n");
      out.write("\t                success: function(data) {\r\n");
      out.write("\t                \tfoodData=data;\r\n");
      out.write("\t                \tconsole.log(data);\r\n");
      out.write("\t                \tconsole.log(foodData[0][\"fname\"]);\r\n");
      out.write("\t                \tfor(var i=0;i<10;i++){\r\n");
      out.write("\t                \t\t\r\n");
      out.write("\t                \t\tif(foodData[i][\"fname\"].length<7){\r\n");
      out.write("\t                \t\tvar foodListData=\"<li><a href='../review/test1.ggd?food=\"+foodData[i][\"fname\"]+\"'style='color:black;' id='a-none'><span><b>\"+(i+1)+\"위</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\"+foodData[i][\"fname\"]+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"</span>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"<span id='ranking'>\"+foodData[i][\"foodcnt\"]+\"&nbsp;<b style='color:red;'>↑</b></span></a>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"</li><br>\"\r\n");
      out.write("\t                \t\t}else{\r\n");
      out.write("\t                \t\t\tvar foodListData=\"<li><a href='../review/test1.ggd?food=\"+foodData[i][\"fname\"]+\"'style='color:black;' id='a-none'><span><b>\"+(i+1)+\"위</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\"+foodData[i][\"fname\"].substring(0,7)+\"...\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"</span>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"<span id='ranking'>\"+foodData[i][\"foodcnt\"]+\"&nbsp;<b align='right' style='color:red;'>↑</b></span></a>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"</li><br>\"\r\n");
      out.write("\t                \t\t}\r\n");
      out.write("\t                \t\t$(\"#foodlist-rank\").append(foodListData);\r\n");
      out.write("\t                \t}\r\n");
      out.write("\t                },\r\n");
      out.write("\t                error: function(){}\t\t\t\r\n");
      out.write("\t\t\t });\r\n");
      out.write("\t\t\t //영화 랭킹 조회\r\n");
      out.write("\t\t\t $.ajax({\r\n");
      out.write("\t                url : '../../springProject/emotion/movierank.ggd',\r\n");
      out.write("\t                type : 'POST',\r\n");
      out.write("\t                async:false,\r\n");
      out.write("\t                datatype:'json',\r\n");
      out.write("\t                success: function(data) {\r\n");
      out.write("\t                \tmovieData=data;\r\n");
      out.write("\t                \tconsole.log(data);\r\n");
      out.write("\t                \tconsole.log(movieData[0][\"mvname\"]);\r\n");
      out.write("\t                \tfor(var i=0;i<10;i++){\r\n");
      out.write("\t                \t\t//<a href='../emotion/moviecount.ggd?movieNum=\"+movieNum[i]+\"&movieLink=\"+movieLink[i]+\"' >\"+\r\n");
      out.write("\t                \t\tif(movieData[i][\"mvname\"].length<7){\r\n");
      out.write("\t                \t\tvar movieListData=\"<li><a href='../emotion/moviecount.ggd?movieNum=\"+movieData[i][\"mvnum\"]+\"&movieLink=\"+movieData[i][\"mvlink\"]+\"'style='color:black;' id='a-none'><span><b>\"+(i+1)+\"위</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\"+movieData[i][\"mvname\"]+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"</span>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"<span id='ranking'>\"+movieData[i][\"moviecnt\"]+\"&nbsp;<b style='color:red;'>↑</b></span>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"</li><br>\"\r\n");
      out.write("\t                \t\t}else{\r\n");
      out.write("\t                \t\t\tvar movieListData=\"<li><a href='../emotion/moviecount.ggd?movieNum=\"+movieData[i][\"mvnum\"]+\"&movieLink=\"+movieData[i][\"mvlink\"]+\"'style='color:black;' id='a-none'><span><b>\"+(i+1)+\"위</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\"+movieData[i][\"mvname\"].substring(0,7)+\"...\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"</span>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"<span id='ranking'>\"+movieData[i][\"moviecnt\"]+\"&nbsp;<b align='right' style='color:red;'>↑</b></span>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"</li><br>\"\r\n");
      out.write("\t                \t\t}\r\n");
      out.write("\t                \t\t$(\"#movielist-rank\").append(movieListData);\r\n");
      out.write("\t                \t}\r\n");
      out.write("\t                },\r\n");
      out.write("\t                error: function(){}\t\t\t\r\n");
      out.write("\t\t\t });\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t}); \r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"click\",\".icon\",function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${seName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"!=''){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#mainForm\").attr(\"action\",\"../../springProject/emotion/emotionSearch.ggd\");\r\n");
      out.write("\t\t\t\t$(\"#mainForm\").attr(\"method\",\"GET\");\r\n");
      out.write("\t\t\t\t$(\"#mainForm\").attr(\"enctype\",\"application/x-www-form-urlencoded\");\r\n");
      out.write("\t\t\t\t$(\"#mainForm\").submit();\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\talert(\"로그인 후 이용해주십시오.\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(document).on(\"click\",\"#loginbtn\",function(){\r\n");
      out.write("\t\t\t$(\"#mainForm\").attr(\"action\",\"../../springProject/logincontroller/loginpage.ggd\");\r\n");
      out.write("\t\t\t$(\"#mainForm\").attr(\"method\",\"POST\");\r\n");
      out.write("\t\t\t$(\"#mainForm\").attr(\"enctype\",\"application/x-www-form-urlencoded\");\r\n");
      out.write("\t\t\t$(\"#mainForm\").submit();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(document).on(\"click\",\"#meminsert\",function(){\r\n");
      out.write("\t\t\t$(\"#mainForm\").attr(\"action\",\"../../springProject/mem/registerForm.ggd\");\r\n");
      out.write("\t\t\t$(\"#mainForm\").attr(\"method\",\"POST\");\r\n");
      out.write("\t\t\t$(\"#mainForm\").attr(\"enctype\",\"application/x-www-form-urlencoded\");\r\n");
      out.write("\t\t\t$(\"#mainForm\").submit();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction logoutBtn(){\r\n");
      out.write("\t\t$(\"#mainForm\").attr(\"action\",\"../emotion/logout.ggd\");\r\n");
      out.write("\t\t$(\"#mainForm\").attr(\"method\",\"POST\");\r\n");
      out.write("\t\t$(\"#mainForm\").attr(\"enctype\",\"application/x-www-form-urlencoded\");\r\n");
      out.write("\t\t$(\"#mainForm\").submit();\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<form name=\"mainForm\" id=\"mainForm\">\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Navbar (sit on top) -->\r\n");
      out.write("<div class=\"w3-top\">\r\n");
      out.write("\t<div class=\"w3-bar w3-white w3-wide w3-padding w3-card\">\r\n");
      out.write("\t\t<a href=\"../../springProject/emotion/mainpage.ggd\">\r\n");
      out.write("\t\t\t<img src=\"/springProject/logo/GOGODA-logo.png\" style=\"width:12%; height:12%\">\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t<!-- Float links to the right. Hide them on small screens -->\r\n");
      out.write("<!--  \t<div align=\"right\" id=\"memlogin\">\r\n");
      out.write("\t\t\t<button type=\"button\" id=\"loginbtn\">로그인</button>\r\n");
      out.write("\t\t\t<button type=\"button\" id=\"meminsert\">회원 가입</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("-->\t\r\n");
      out.write("\t\t\r\n");
      out.write("    <div class=\"w3-right w3-hide-small\" id=\"memlogin\">\r\n");
      out.write("\t\t<a href=\"#로그인\" class=\"w3-bar-item w3-button\" id=\"loginbtn\">로그인</a>\r\n");
      out.write("\t\t<a href=\"#회원 가입\" class=\"w3-bar-item w3-button\" id=\"meminsert\">회원가입</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<br>\r\n");
      out.write("<!-- Header -->\r\n");
      out.write("<header class=\"w3-display-container w3-content w3-wide\" style=\"max-width:1500px;\" id=\"home\">\r\n");
      out.write("\t<img class=\"w3-image\" src=\"/springProject/logo/applepie.png\" alt=\"Applepie\" width=\"1500\" height=\"800\">\r\n");
      out.write("\t<div class=\"w3-display-middle w3-margin-top w3-center\">\r\n");
      out.write("\t<!-- \r\n");
      out.write("\t\t<h1 class=\"w3-xxlarge w3-text-white\"> <span class=\"w3-hide-small w3-text-light-grey\">맛있</span><span class=\"w3-padding w3-black w3-opacity-min\"><b>GO</b></span></h1>\r\n");
      out.write("\t\t<h1 class=\"w3-xxlarge w3-text-white\"> <span class=\"w3-hide-small w3-text-light-grey\">재밌</span><span class=\"w3-padding w3-black w3-opacity-min\"><b>GO</b></span></h1>\r\n");
      out.write("\t\t<h1 class=\"w3-xxlarge w3-text-white\"> <span class=\"w3-hide-small w3-text-light-grey\">신난</span><span class=\"w3-padding w3-black w3-opacity-min\"><b>DA</b></span></h1>\r\n");
      out.write("\t -->\r\n");
      out.write("\t \t<div class=\"box\" align=\"center\">\r\n");
      out.write("\t\t\t<div class=\"container-1\">\r\n");
      out.write("\t\t\t\t<span class=\"icon\"><i class=\"fa fa-search\"></i></span>\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"text\" name=\"text\" style=\"width: 700px; height:55px;'\" placeholder=\"오늘 어떤 일이 있으셨나요?\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<!-- Page content -->\r\n");
      out.write("<div class=\"w3-content w3-padding\" style=\"max-width:1564px\">\r\n");
      out.write("\t<div id=\"topboard\" align=\"center\" style=\"position: relative; z-index: 0; overflow: hidden; min-width: 100%; height: 100%; touch-action: pan-x; user-select: none; -webkit-user-drag: none; width: 210px;\">\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("  <div id=\"under\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td id=\"under-table\"><!-- white -->\r\n");
      out.write("\t\t\t\t\t<table class=\"board-wi-he\" bgcolor=\"white\" border='0'\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"border-style:solid;border-width:0px;border-color:#c2c1c6; margin-bottom: 5px; \" >\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td id=\"line-title\"style=\"font-size:14px;font-weight:bold;\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>게시글</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href='../../springProject/board/boardList.ggd' style='color:black' id='a-none'><span style=\"width: 500px; display: inline-block; float: right; font-size:12px;\" align=\"right\">더보기</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<td id=\"line-title\" class=\"rank-table-food\" style=\"font-size:14px;font-weight:bold;\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span style=\"width: 180px; display: inline-block; float: left;\" align=\"left\">음식 랭킹</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td id=\"line-title\" class=\"rank-table-movie\" style=\"font-size:14px;font-weight:bold;\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span style=\"width: 180px; display: inline-block; float: left;\" align=\"left\">영화 랭킹</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"width:50%;\" id=\"boardlist-main\" name=\"boardlist-main\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"rank-table-food\" id=\"foodlist-rank\" name=\"foodlist-rank\" style=\"font-size:13px;\" align=\"top\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"rank-table-movie\" id=\"movielist-rank\"style=\"font-size:13px;\" align=\"top\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Footer -->\r\n");
      out.write("<footer class=\"w3-center w3-black w3-padding-16\">\r\n");
      out.write("  <p>Powered by <a href=\"../../springProject/emotion/mainpage.ggd\" title=\"GOGODA\" target=\"_blank\" class=\"w3-hover-text-green\">GOGODA</a></p>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</form>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
