/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.60
 * Generated at: 2021-03-05 10:05:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/00.KOSMO72/eclipse_springproject_work/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/springProject/WEB-INF/lib/standard.jar!/META-INF/fn.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1610932211247L));
    _jspx_dependants.put("jar:file:/C:/00.KOSMO72/eclipse_springproject_work/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/springProject/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0,\r\n");
      out.write("\t  maximum-scale=1.0, minimum-scale=1.0, user-scalable=no\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compaible\" content=\"IE=edge,chrome=1\" />\r\n");
      out.write("<title>글상세 보기</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/include/css/main.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/include/css/board.css\" />\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/include/js/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/include/js/common.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\tvar butChk = 0; // 수정버튼과 삭제버튼을 구별하기 위한 변수\r\n");
      out.write("\t\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$(\"#pwdChk\").hide();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 첨부파일 이미지 보여주기 위한 속성 추가*/\r\n");
      out.write("\t\tvar file = \"");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("\";\r\n");
      out.write("\t\tif (file!=\"\") {\r\n");
      out.write("\t\t\t \t$(\"#fileImage\").attr({\r\n");
      out.write("\t\t\t \t\t\tsrc:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/uploadStorage/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.bfile}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\",\r\n");
      out.write("\t\t\t \t\t\twidth:\"250px\",\r\n");
      out.write("\t\t\t \t\t\theight:\"200px\"\r\n");
      out.write("\t\t\t \t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/*수정 버튼 클릭 시 처리 이벤트*/\r\n");
      out.write("\t\t$(\"#updateForm\").click(function(){\r\n");
      out.write("\t\t\tif(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${seName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"!=''){\r\n");
      out.write("\t\t\t\t$(\"#pwdChk\").show();\r\n");
      out.write("\t\t\t\t$(\"#msg\").text(\"비밀번호를 입력해 주세요.\").css(\"color\",\"#000099\");\r\n");
      out.write("\t\t\t\tbutChk = 1;\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\talert(\"로그인 상태를 확인해주세요\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t/*삭제 버튼 클릭 시 처리 이벤트*/\r\n");
      out.write("\t\t$(\"#boardDelete\").click(function(){\r\n");
      out.write("\t\t\tif(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${seName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"!=''){\r\n");
      out.write("\t\t\t\t$(\"#pwdChk\").show();\r\n");
      out.write("\t\t\t\t$(\"#msg\").text(\"비밀번호를 입력해 주세요.\").css(\"color\",\"#000099\");\r\n");
      out.write("\t\t\t\tbutChk = 2;\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\talert(\"로그인 상태를 확인해주세요.\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/*비밀번호 확인 버튼 클릭 시 처리 이벤트*/\r\n");
      out.write("\t\t$(\"#pwdBut\").click(function(){\r\n");
      out.write("\t\t\t\tpwdConfirm();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/*목록 버튼 클릭 시 처리 이벤트*/\r\n");
      out.write("\t\t$(\"#boardList\").click(function(){\r\n");
      out.write("\t\t\t\tlocation.href=\"boardList.ggd\";\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t/*비밀번호 확인 버튼 클릭시 실질적인 처리 함수*/\r\n");
      out.write("\tfunction pwdConfirm(){\r\n");
      out.write("\t\tif (!chkSubmit($(\"#bpw\"),\"비밀번호를\")) return; \r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl:\"pwdConfirm.ggd\", \t// 전송 url\r\n");
      out.write("\t\t\t\ttype:\"POST\",\t\t\t\t \t// 전송 시 method 방식\r\n");
      out.write("\t\t\t\tdata:$(\"#f_pwd\").serialize(),\t// 폼전체 데이터 전송\r\n");
      out.write("\t\t\t\terror:function(){\t\t\t\t// 실행시 오류가 발생하였을 경우\r\n");
      out.write("\t\t\t\t\talert('시스템 오류입니다. 관리자에게 문의 하세요');\r\n");
      out.write("\t\t\t\t},\t\t\t\t\t\t\t\t// 정상적으로 실행이 되었을 경우\r\n");
      out.write("\t\t\t\tsuccess:function(resultData){\r\n");
      out.write("\t\t\t\t\tvar goUrl=\"\";\t\t\t\t// 이동할 경로를 저장할 변수\r\n");
      out.write("\t\t\t\t\tif (resultData == 0) {\t\t// 일치하지 않는 경우\r\n");
      out.write("\t\t\t\t\t\t$(\"#msg\").text(\"비밀번호가 일치하지 않습니다.\").css(\"color\",\"red\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#bpw\").select();\r\n");
      out.write("\t\t\t\t\t}else if (resultData == 1) { // 일치할 경우\r\n");
      out.write("\t\t\t\t\t\t$(\"#msg\").text(\"\");\r\n");
      out.write("\t\t\t\t\t\tif (butChk == 1) {\r\n");
      out.write("\t\t\t\t\t\t\tgoUrl = \"updateForm.ggd\";\r\n");
      out.write("\t\t\t\t\t\t} else if(butChk == 2){\r\n");
      out.write("\t\t\t\t\t\t\tgoUrl = \"boardDelete.ggd\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t$(\"#f_data\").attr(\"action\",goUrl);\r\n");
      out.write("\t\t\t\t\t\t$(\"#f_data\").submit();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- Navbar (sit on top) -->\r\n");
      out.write("<div class=\"w3-top\">\r\n");
      out.write("\t<div class=\"w3-bar w3-white w3-wide w3-padding w3-card\">\r\n");
      out.write("\t\t<a href=\"../../springProject/emotion/mainpage.ggd\">\r\n");
      out.write("\t\t\t<img src=\"/springProject/logo/GOGODA-logo.png\" style=\"width:12%; height:12%\">\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div><br><br><br><br><br><br>\r\n");
      out.write("<!-- Header -->\r\n");
      out.write("<header class=\"display-container\" style=\"max-width:1500px;\" id=\"home\">\r\n");
      out.write("\t<img class=\"applepie-image\" src=\"/springProject/logo/applepie.png\" alt=\"Applepie\" width=\"1500\" height=\"1000\">\r\n");
      out.write("\t<div class=\"board-display\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"boardContainer\" align=\"left\">\r\n");
      out.write("<!-- \r\n");
      out.write("\t<div id=\"Detailtop\">\r\n");
      out.write("\t<a href=\"../../springProject/emotion/mainpage.ggd\">\r\n");
      out.write("\t\t<img src=\"../images/common/gogoda.png\" style=\"width:170px; height:170px\" />\r\n");
      out.write("\t</a>\r\n");
      out.write("\t</div>  -->\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"boardTit\"><h2><b>글 상세 조회</b></h2></div>\r\n");
      out.write("\t<form name=\"f_data\" id=\"f_data\" method=\"POST\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"bnum\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.bnum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"bfile\" id=\"bfile\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.bfile}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t</form>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t<table id=\"boardPwdBut\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td id=\"btd1\"> \r\n");
      out.write("\t\t\t\t<div id=\"pwdChk\">\r\n");
      out.write("\t\t\t\t\t<form name=\"f_pwd\" id=\"f_pwd\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"bnum\" id=\"bnum\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.bnum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t<label for=\"bpw\" id=\"l_pwd\"></label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" name=\"bpw\" id=\"bpw\" />\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" id=\"pwdBut\" value=\"확인\" />\r\n");
      out.write("\t\t\t\t\t\t<span id=\"msg\"></span>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td id=\"btd2\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"수정\" id=\"updateForm\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"삭제\" id=\"boardDelete\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"목록\" id=\"boardList\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t<div id=\"boardDetail\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t<col width=\"20%\" />\r\n");
      out.write("\t\t\t\t<col width=\"30%\" />\r\n");
      out.write("\t\t\t\t<col width=\"20%\" />\r\n");
      out.write("\t\t\t\t<col width=\"30%\" />\r\n");
      out.write("\t\t\t</colgroup>\r\n");
      out.write("\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"ac\">글쓴이</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.bname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"ac\">작성일</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.binsertdate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"ac\">제목</td>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"3\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.bsubject}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr class=\"ctr\">\r\n");
      out.write("\t\t\t\t\t<td class=\"ac\">내용</td>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"3\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.bcontent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr class=\"ctr\">\r\n");
      out.write("\t\t\t\t\t<td class=\"ac\">사진</td>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"3\"><img id=\"fileImage\" width=\"150px\" height=\"100px\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "rboard.jsp", out, false);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("</header>\r\n");
      out.write("<!-- Footer-->\r\n");
      out.write("<footer class=\"w3-center w3-black w3-padding-16\">\r\n");
      out.write("  <p>Powered by <a href=\"../../springProject/emotion/mainpage.ggd\" title=\"GOGODA\" target=\"_blank\" class=\"w3-hover-text-green\">GOGODA</a></p>\r\n");
      out.write("</footer>  \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /WEB-INF/view/board/boardDetail.jsp(27,14) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.bfile}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }
}
