/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.60
 * Generated at: 2021-02-26 06:54:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class writeForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/00.KOSMO72/eclipse_springproject_work/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/springProject/WEB-INF/lib/standard.jar!/META-INF/fn.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1610932211247L));
    _jspx_dependants.put("jar:file:/C:/00.KOSMO72/eclipse_springproject_work/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/springProject/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0,\r\n");
      out.write("\t  maximum-scale=1.0, minimum-scale=1.0, user-scalable=no\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compaible\" content=\"IE=edge,chrome=1\" />\r\n");
      out.write("<title>글쓰기 화면</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/include/css/board.css\" />\r\n");
      out.write("<!-- 웹에디터 -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/se2/js/service/HuskyEZCreator.js\" charset=\"UTF-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/include/js/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/include/js/common.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).ready(function(){\t\r\n");
      out.write("\t\r\n");
      out.write("\t\tvar oEditors = [];\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\tnhn.husky.EZCreator.createInIFrame({\r\n");
      out.write("\t\t\t\toAppRef : oEditors,\r\n");
      out.write("\t\t\t\telPlaceHolder : \"bcontent\", // textarea id \t\t\t\t\r\n");
      out.write("\t\t\t\tsSkinURI : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/se2/SmartEditor2Skin.html\", // SmartEditor2Skin.html 에디터 스킨 \t\t\t\t\r\n");
      out.write("\t\t\t\tfCreator : \"createSEditor2\"\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t$(document).on(\"click\", \"#boardInsert\", function(){\r\n");
      out.write("\t\t\tconsole.log(\"boardInsert >>> : \");\t\r\n");
      out.write("\t\t\toEditors.getById[\"bcontent\"].exec(\"UPDATE_CONTENTS_FIELD\", []);\t\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#f_writeForm').attr({\r\n");
      out.write("\t\t\t\t'action':'boardInsert.ggd',\r\n");
      out.write("\t\t\t\t'method':'POST',\r\n");
      out.write("\t\t\t\t'enctype':'multipart/form-data'\r\n");
      out.write("\t\t\t}).submit();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t/*저장 버튼 클릭 시 처리 이벤트*/\r\n");
      out.write("\t\t$(\"#boardInsert\").click(function(){\r\n");
      out.write("\t\t\talert(('#bcontent').val().replace('?',''));\r\n");
      out.write("\t\t\t// 입력값 체크\r\n");
      out.write("\t\t\tif (!chkSubmit($('#bname'),\"이름을\")) return;\r\n");
      out.write("\t\t\telse if (!chkSubmit($('#bsubject'),\"제목을\")) return;\r\n");
      out.write("\t\t\t// else if (!chkSubmit($('#bcontent'),\"작성할 내용을\")) return;\r\n");
      out.write("\t\t\telse if (!chkSubmit($('#file'),\"첨부파일을\")) return;\r\n");
      out.write("\t\t\telse if (!chkSubmit($('#bpw'),\"비밀번호를\")) return;\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t/*배열내의 값을 찾아서 인덱스를 반환(요소가 없을 경우 -1 반환 )\r\n");
      out.write("\t\t\t\tjQuery.inArray(찾을 값,검색 대상의 배열)*/\r\n");
      out.write("\t\t\t\t\tvar ext = $('#file').val().split('.').pop().toLowerCase();\r\n");
      out.write("\t\t\t\t\tif (jQuery.inArray(ext, ['gif','png','jpg','jpeg']) == -1) {\r\n");
      out.write("\t\t\t\t\t\t \talert('gif,png,jpg,jpeg 파일만 업로드 할 수 있습니다.');\r\n");
      out.write("\t\t\t\t\t\t \treturn;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$(\"#f_writeForm\").attr({\r\n");
      out.write("\t\t\t\t\t\t\t\"method\":\"POST\",\r\n");
      out.write("\t\t\t\t\t\t\t\"action\":\"/boardInsert.ggd\"\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t$(\"#f_writeForm\").submit();\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t        });\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t/*목록 버튼 클릭 시 처리 이벤트*/\r\n");
      out.write("\t\t\t\t\t$(\"#boardList\").click(function(){\r\n");
      out.write("\t\t\t\t\t\tlocation.href=\"boardList.ggd\";\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"writetop\">\r\n");
      out.write("\t<a href=\"http://google.com\" target=\"_blank\">\r\n");
      out.write("\t\t<img src=\"../images/common/gogoda.png\" style=\"width:150px; height:100px\" />\r\n");
      out.write("\t</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"boardTit\"><h3>글쓰기</h3></div>\r\n");
      out.write("\t<form id=\"f_writeForm\" name=\"f_writeForm\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t<table id=\"boardWrite\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>글쓴이</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"bname\" id=\"bname\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>글제목</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"bsubject\" id=\"bsubject\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>내용</td>\r\n");
      out.write("\t\t\t\t<td height=\"200\"><textarea name=\"bcontent\" id=\"bcontent\"\r\n");
      out.write("\t\t\t\t\t\t\t\trows=\"10\" cols=\"70\"></textarea></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>첨부파일</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"file\" name=\"file\" id=\"file\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>비밀번호</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"password\" name=\"bpw\" id=\"bpw\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<div id=\"boardBut\">\r\n");
      out.write("\t\t<input type=\"button\" value=\"저장\" class=\"but\" id=\"boardInsert\">\r\n");
      out.write("\t\t<input type=\"button\" value=\"목록\" class=\"but\" id=\"boardList\">\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
